/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Cantina(props) {
  const { nodes, materials } = useGLTF("./models/HassenCantina.glb");
  return (
    <group {...props} dispose={null} 
          //We make sure that we can't click through this object.
           onPointerDown = { (e) => e.stopPropagation() } 
           onPointerOver = { (e) => e.stopPropagation() } 
           onPointerOut  = { (e) => e.stopPropagation() } >
      <group position={[0, 10, 0]} scale={[20, 10, 20]}>
        <group position={[-0.393, -0.71, -0.607]} scale={[0.05, 0.1, 0.05]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube025.geometry}
            material={materials.CubeCrateMaterial1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube025_1.geometry}
            material={materials.CubeCrateMaterial2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube025_2.geometry}
            material={materials.BigCrateScreenMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube025_3.geometry}
            material={materials.BigCrateRedButtonMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube025_4.geometry}
            material={materials.BigCrateGreenButtonMaterial}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BigPipe.geometry}
          material={materials.PipeMaterial}
          position={[-0.35, -1, 0.8]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.05, 0.05, 0.1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BigUndergroundPipe.geometry}
          material={materials.PipeMaterial}
          position={[0.478, -0.815, -1.194]}
          rotation={[Math.PI / 2, 0, Math.PI / 3]}
          scale={[0.05, 0.05, 0.1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Bottle006.geometry}
          material={materials.BottleMaterial}
          position={[0, -1, 0]}
          scale={[0.05, 0.1, 0.05]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ClassyGlass.geometry}
          material={materials["Material.004"]}
          position={[0.383, -0.437, -0.266]}
          scale={[0.012, 0.024, 0.012]}
        />
        <group position={[0.307, -1.391, 1.006]} scale={[0.05, 0.1, 0.05]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder004.geometry}
            material={materials.CylinderCrateMaterial1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder004_1.geometry}
            material={materials.CylinderCrateMaterial2}
          />
        </group>
        <group position={[0, -1.005, 0]} scale={[0.05, 0.1, 0.05]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder008.geometry}
            material={materials.CylinderCrateMaterial1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder008_1.geometry}
            material={materials.CylinderCrateMaterial2}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Etagere.geometry}
          material={materials["BarTopMaterial.001"]}
          position={[0.301, -0.042, -0.774]}
          scale={[0.05, 0.1, 0.05]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Bottle001.geometry}
            material={materials.BottleMaterial}
            position={[1.373, -0.451, -0.033]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Bottle2.geometry}
            material={materials.WeirdBottle}
            position={[0.129, -1.099, -0.036]}
            scale={0.645}
          />
        </mesh>
        <group position={[0, -1, 0]} scale={[0.05, 0.1, 0.05]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube004.geometry}
            material={materials.CratePrimaryMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube004_1.geometry}
            material={materials.CrateSecondaryMaterial}
          />
        </group>
        <group position={[0, -1, 0]} scale={[0.05, 0.1, 0.05]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube005.geometry}
            material={materials.CratePrimaryMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube005_1.geometry}
            material={materials.CrateSecondaryMaterial}
          />
        </group>
        <group position={[0, -1, 0]} scale={[0.05, 0.1, 0.05]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube006.geometry}
            material={materials.CratePrimaryMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube006_1.geometry}
            material={materials.CrateSecondaryMaterial}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Glass.geometry}
          material={materials.GlassMaterial}
          position={[0.027, -0.409, 0.246]}
          scale={[0.05, 0.1, 0.05]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Glass001.geometry}
          material={materials.GlassMaterial}
          position={[-2.871, -0.685, 0.451]}
          scale={[0.05, 0.1, 0.05]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.InDoorPipe.geometry}
          material={materials.PipeMaterial}
          position={[-2.47, -0.903, 0.032]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[0.05, 0.05, 0.1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LampHolder.geometry}
          material={materials.LampHolderMaterial}
          position={[0, -1, 0]}
          scale={[0.05, 0.1, 0.05]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LampHolder001.geometry}
          material={materials.LampHolderMaterial}
          position={[0, -1, 0]}
          scale={[0.05, 0.1, 0.05]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line.geometry}
          material={materials.DoorMaterial}
          position={[-0.102, 0.2, 0.027]}
          scale={[0.05, 0.1, 0.05]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line2.geometry}
          material={materials.DoorMaterial}
          position={[-0.102, 0.169, 0.013]}
          scale={[0.05, 0.1, 0.05]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3.geometry}
          material={materials.DoorMaterial}
          position={[-0.102, 0.126, -0.012]}
          scale={[0.05, 0.1, 0.05]}
        />
        <group position={[0, -1, 0]} scale={[0.05, 0.1, 0.05]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube001.geometry}
            material={materials.WallsMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube001_1.geometry}
            material={materials.WallsMaterial}
          />
        </group>
        <group position={[0.101, -0.664, -0.644]} scale={[0.05, 0.1, 0.05]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube031.geometry}
            material={materials.WallsMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube031_1.geometry}
            material={materials["BarTopMaterial.001"]}
          />
        </group>
        <group
          position={[0.51, -0.748, -0.599]}
          rotation={[0, 0.72, 0]}
          scale={[0.05, 0.1, 0.05]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.StoolDown.geometry}
            material={materials.StoolBackMaterial}
            position={[-0.016, 1.588, 0.012]}
            rotation={[0, Math.PI / 2, 0]}
          />
          <group
            position={[-0.016, 1.588, 0.012]}
            rotation={[0, Math.PI / 2, 0]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder009.geometry}
              material={materials.StoolMaterial}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder009_1.geometry}
              material={materials.StoolBackMaterial}
            />
          </group>
        </group>
        <group
          position={[0.003, -0.75, 0.393]}
          rotation={[Math.PI, -0.849, Math.PI]}
          scale={[0.05, 0.1, 0.05]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.StoolDown001.geometry}
            material={materials.StoolBackMaterial}
            position={[-0.016, 1.588, 0.012]}
            rotation={[0, Math.PI / 2, 0]}
          />
          <group
            position={[-0.016, 1.588, 0.012]}
            rotation={[0, Math.PI / 2, 0]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder011.geometry}
              material={materials.StoolMaterial}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder011_1.geometry}
              material={materials.StoolBackMaterial}
            />
          </group>
        </group>
        <group
          position={[0.227, -0.75, 0.312]}
          rotation={[0, 0.519, 0]}
          scale={[0.05, 0.1, 0.05]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.StoolDown002.geometry}
            material={materials.StoolBackMaterial}
            position={[-0.016, 1.588, 0.012]}
            rotation={[0, Math.PI / 2, 0]}
          />
          <group
            position={[-0.016, 1.588, 0.012]}
            rotation={[0, Math.PI / 2, 0]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder013.geometry}
              material={materials.StoolMaterial}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder013_1.geometry}
              material={materials.StoolBackMaterial}
            />
          </group>
        </group>
        <group
          position={[0.502, -0.755, -0.264]}
          rotation={[0, -0.004, 0]}
          scale={[0.05, 0.1, 0.05]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.StoolDown003.geometry}
            material={materials.StoolBackMaterial}
            position={[-0.016, 1.588, 0.012]}
            rotation={[0, Math.PI / 2, 0]}
          />
          <group
            position={[-0.016, 1.588, 0.012]}
            rotation={[0, Math.PI / 2, 0]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder015.geometry}
              material={materials.StoolMaterial}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder015_1.geometry}
              material={materials.StoolBackMaterial}
            />
          </group>
        </group>
        <group
          position={[0.46, -0.75, 0]}
          rotation={[0, -0.281, 0]}
          scale={[0.05, 0.1, 0.05]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.StoolDown004.geometry}
            material={materials.StoolBackMaterial}
            position={[-0.016, 1.588, 0.012]}
            rotation={[0, Math.PI / 2, 0]}
          />
          <group
            position={[-0.016, 1.588, 0.012]}
            rotation={[0, Math.PI / 2, 0]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder017.geometry}
              material={materials.StoolMaterial}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder017_1.geometry}
              material={materials.StoolBackMaterial}
            />
          </group>
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SmallGlass.geometry}
          material={materials.GlassMaterial}
          position={[0.37, -0.44, -0.587]}
          scale={[0.05, 0.1, 0.05]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SmallGlass001.geometry}
          material={materials.GlassMaterial}
          position={[0.357, -0.44, -0.569]}
          scale={[0.05, 0.1, 0.05]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SmallGlass002.geometry}
          material={materials.GlassMaterial}
          position={[0.342, -0.44, -0.588]}
          scale={[0.05, 0.1, 0.05]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SmallGlass003.geometry}
          material={materials.GlassMaterial}
          position={[0.388, -0.44, -0.527]}
          scale={[0.05, 0.1, 0.05]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SmallPipe.geometry}
          material={materials.PipeMaterial}
          position={[-0.332, -1, 0.65]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.05, 0.05, 0.1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SmallPipe001.geometry}
          material={materials.PipeMaterial}
          position={[-0.334, -1, 0.55]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.05, 0.05, 0.1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SmallPipe002.geometry}
          material={materials.PipeMaterial}
          position={[-0.133, -0.765, 0.573]}
          scale={[0.05, 0.1, 0.05]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SmallPipe1.geometry}
          material={materials.PipeMaterial}
          position={[-0.133, -0.879, 0.017]}
          scale={[0.05, 0.1, 0.05]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SmallPipe2.geometry}
          material={materials.PipeMaterial}
          position={[-0.133, -0.879, 0.017]}
          scale={[0.05, 0.1, 0.05]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SmallPipe3.geometry}
          material={materials.PipeMaterial}
          position={[-0.133, -0.949, 0.146]}
          scale={[0.05, 0.1, 0.05]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SpecialBottle.geometry}
          material={materials.SpecialBottleMaterial}
          position={[0.237, -0.139, -0.784]}
          scale={[0.05, 0.1, 0.05]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder.geometry}
            material={materials["Material.005"]}
            position={[0, 1.998, 0.001]}
            rotation={[-Math.PI, 0, 0]}
            scale={0.124}
          />
        </mesh>
        <group position={[0, -1, 0]} scale={[0.05, 0.1, 0.05]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001.geometry}
            material={materials.StreetLampMaterial1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001_1.geometry}
            material={materials.StreetLampMaterial2}
          />
        </group>
        <group position={[0.739, -0.269, 0.67]} scale={[0.05, 0.1, 0.05]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube015.geometry}
            material={materials.DoorMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube015_1.geometry}
            material={materials.BigCrateRedButtonMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube015_2.geometry}
            material={materials.BigCrateGreenButtonMaterial}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DoorOutlines.geometry}
          material={materials.DoorOutlineMaterial}
          position={[0.348, -0.286, 0.872]}
          scale={[0.05, 0.1, 0.05]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DoorOutlines001.geometry}
          material={materials.DoorOutlineMaterial}
          position={[0.348, -0.286, 0.872]}
          scale={[0.05, 0.1, 0.05]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ElectricBox.geometry}
          material={materials.Electric}
          position={[-0.058, 0.258, 0.908]}
          scale={[0.05, 0.1, 0.05]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ElectricLine.geometry}
          material={materials.Electric}
          position={[0.303, 0.262, 0.899]}
          scale={[0.05, 0.1, 0.05]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ElectricLine001.geometry}
          material={materials.Electric}
          position={[0.297, 0.249, 0.899]}
          scale={[0.05, 0.1, 0.05]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ElectricLine002.geometry}
          material={materials.Electric}
          position={[0.294, 0.23, 0.899]}
          scale={[0.05, 0.1, 0.05]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MainDoor.geometry}
          material={materials.DoorMaterial}
          position={[0.35, -0.023, 0.849]}
          scale={[0.05, 0.095, 0.007]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./models/HassenCantina.glb");
