/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Communicator(props) {
  const { nodes, materials } = useGLTF("./models/Communicator.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.981, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube.geometry}
          material={materials.MainComMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_1.geometry}
          material={materials.BlueMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_2.geometry}
          material={materials.RedMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_3.geometry}
          material={materials.RedMaterial}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./models/Communicator.glb");
