/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function PublicityDisplay(props) {
  const { nodes, materials } = useGLTF("./models/PublicityDisplay.glb");
  return (
    <group {...props} dispose={null}
            //We make sure that we can't click through this object.
            onPointerDown = { (e) => e.stopPropagation() } 
            onPointerOver = { (e) => e.stopPropagation() } 
            onPointerOut  = { (e) => e.stopPropagation() }>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MainScreen.geometry}
        material={materials.DefaultMaterial}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Holder.geometry}
        material={materials.DefaultMaterial}
      />
    </group>
  );
}

useGLTF.preload("./models/PublicityDisplay.glb");
